apiVersion: v1
kind: ConfigMap
metadata:
  name: bfa2-configmap
  namespace: default


data:
  DB_NAME: bfa_app
  DB_USER: user
  DB_PASSWORD: password 
  DB_HOST: localhost
  DB_PORT: "8888"
  DB_TYPE: sqlite
  JWT_SECRET: LOve-yours-
  MAIL_USERNAME: bigfastapi
  MAIL_PASSWORD: password
  MAIL_FROM: "bigfast@api.com"
  MAIL_PORT: "593"
  MAIL_SERVER: "mail.example.com"
  MAIL_FROM_NAME: BigFast
  TEMPLATE_FOLDER: "bigfastapi/templates"
  EMAIL_VERIFICATION_TEMPLATE: "email/welcome_email.html"
  PASSWORD_RESET_TEMPLATE:  "email/password_reset.html"
  FILES_BASE_FOLDER: filestorage
  FLUTTERWAVE_SEC_KEY: nil
  STRIPE_SEC_KEY: nil
  GOOGLE_CLIENT_ID: nil
  GOOGLE_CLIENT_SECRET: nil
  GOOGLE_SECRET: nil
  REDIRECT_URL: nil
  API_URL: "http://bigfastapi.info"
  FRONTEND_URL: nil
  FREECURRENCY_API_KEY: nil 
  DEFAULT_CREDIT_WALLET_BALANCE: nil
  BASE_URL: nil
  API_REDIRECT_URL: nil
