{{- range .Values.versions }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}

spec:
  type: {{ .service.type }}
  ports:
  - port: {{ .service.port }}
    targetPort: {{ .deployment.containerPort }}
  selector:
    app: {{ .name }}




{{- end }}


